# Generated by Django 4.1.4 on 2023-02-10 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_offers_dicount_offers_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='end_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='offers',
            name='start_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
